services:
  web:
    build: .
    ports:
      - "5000:5000"
    image: cfaprdbatchcr.azurecr.io/config-validation-service:latest
    environment:
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
