name: deploy

# TODO remove the pull request, only use for testing
on:
  pull_request:
  push:
    branches: [master]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Azure Service Principal CLI login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Docker
      uses: docker/setup-buildx-action@v3

    - name: Azure ACR login
      uses: azure/docker-login@v2
      with:
        login-server: cfaprdconfigvalidation.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build image
      run: docker-compose build --no-cache
