name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: cache poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: install poetry
        run: pip install poetry

      - name: install api packages
        run: poetry install

      - name: run tests
        run: poetry run pytest
